# Setup
title:        Adam Storer
tagline:      ""
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Adam Storer
  url:

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
port: "3000"

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
