# Setup
title:        Adam Storer
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Adam Storer 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
