# Setup
title:        Adam Storer
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Adam Storer
  url:

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
port: "3000"
